\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename message.info
@include version.texi
@settitle Message NodeBrain Module
@c %**end of header

@finalout
@paragraphindent none
@setchapternewpage odd

@copying
Message NodeBrain Module@*
January, 2011@*
The Boeing Company,  P.O. Box 3707, Seattle, WA 98124, USA

@sp 2
@b{Version @value{VERSION}} 

Author: Ed Trettevik <ed.a.trettevik@@boeing.com>

Copyright @copyright{} 2010, 2011 The Boeing Company.

@sp 1
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or any later version published by the Free Software Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A copy of the license is included in the section titled @i{GNU Free Documentation License} preceding the index at the end of this document.

@sp 1
NodeBrain(TM) is a trademark of The Boeing Company.   All other trademarks and registered trademarks referenced in this document are the trademarks of their respective owners.

@sp 2
@b{Software License}

@multitable {------------------------------} {----------------------------------------------------}

@item Copyright @copyright{} 2010, 2011 @tab The Boeing Company
@item @tab Ed Trettevik <eat@@nodebrain.org>
@end multitable

The Message NodeBrain Module is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option)any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program; if not, write to Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
@end copying

@iftex
@titlepage
@c @image{./image001,32pt,32pt,,gif}

@titlefont{Message NodeBrain Module}
@sp 1
@tex
\vskip4pt \hrule height 3pt width \hsize
@end tex
@sp 3
@b{Version @value{VERSION}}
@page
@vskip 0pt plus 1filll
@insertcopying

@c History Preface and Document Conventions 
@page
@b{History}

@multitable {-------------} {--------------------------------------------------------------------------------------------------------}
@item 2010-09-13 @tab
Title: @i{Message NodeBrain Module}@*  
Author: Ed  Trettevik <ed.a.trettevik@@boeing.com>@*
Publisher: The Boeing Company

@item @tab
Version 0.1
@itemize @bullet
@item Initial prototype.
This document describes the Message module as released with NodeBrain 0.8.5.
We anticipate changes to this document as the module evolves to a version 1.0.
@end itemize

@c @item 2010-02-06 @tab   
@c Version 0.2
@c @itemize @bullet
@c @item This update follows installation of Bingo 0.2 in a test environment.  It is not an entirely
@c accurate description of Bingo 0.2 software.  We are continuing to use this document as a specification
@c document, with version 1.0 being the target. Bingo 0.2 has some deficiencies relative to this document,
@c and may also include functionality not yet documented here.
@c @end itemize

@end multitable

@page
@b{Preface}

@sp 1
This manual is intended for users of the Message NodeBrain Module, a plug-in for broadcasting messages
to a set of NodeBrain agents.
The Message module was first introduced in NodeBrain 0.8.0 in early 2010.  
This module should be treated as a prototype.  It has not yet been exercised enough to fully validate the design.
We expect it to evolve as we gain experience.

This module was developed in support of a specific application requiring multi-master replication of data objects
managed by a proprietary module.  
However, it provides a generic message server and a NodeBrain command-specific message client,
making it useful to various NodeBrain applications.
Custom modules can use the NodeBrain Message API to implement application-specific message clients.  It is the
responsibility of a message client to handle conflict resolution.

In November 2010, this module was first used in a production application supporting a form
of user authentication requiring high availability.


@end titlepage
@end iftex

@c ----------------------------------------------------------
@c Not printed document

@ifnottex
@node Top
@top Message NodeBrain Module @value{VERSION}

This manual is for the Message NodeBrain Module (version @value{VERSION}, @value{UPDATED}), a plug-in module for broadcasting
messages to multiple NodeBrain agents.

Copyright @copyright{} 2010, 2011 The Boeing Company.

@ifnotplaintext
@b{Short Table of Contents}
@end ifnotplaintext
@menu
* Concepts:: Foundation
* Tutorial:: Introduction by Example
* Commands:: Syntax and Semantics
* Triggers:: Conditions and Response
@end menu

@ifnotplaintext
@b{References}
@end ifnotplaintext
@menu
* GNU Free Documentation License::
* Index::
@end menu
@end ifnottex

@c Set page footings
@oddfooting @thistitle @| @| @thispage
@evenfooting @thispage @| @| @thistitle

@c Table of Contents
@oddheading @| @| 
@evenheading @| @|
@contents

@c Set page headings for document
@oddheading @thischapter @| @| @value{UPDATED-MONTH}
@evenheading @value{UPDATED-MONTH} @| @| @thischapter

@node Concepts
@chapter Concepts
@cindex concepts

The Message module is a NodeBrain plug-in for broadcasting messages to multiple peers. 
It uses the NodeBrain Message API, which is also available to other modules.
Here we introduce some basic concepts of the API.


@section Message Log
@cindex message log

A message log is a directory containing files used to manage the delivery of messages from one node to another within a set of nodes that share messages.  This set of nodes is a "cabal."
The relative path for a message log directory within a NodeBrain caboodle is @code{message/@i{cabal}/@i{node}}.

@multitable {-----------------------} {-----------------------------------------------------------------------------------------}
@item @code{@i{name}.msg}@w{         }
@tab A named message file identifies the last message received from every node within a cabal.
This information is the "state" of the node and a named message file is sometimes referred to as a "state file."
This file may be a symbolic link to the active numbered message file.

@item @code{@i{nnnnnnnn}.msg}
@tab A numbered message file contains a header providing the log's state at the time the file was started.
This is followed by a set of message records.
The number @i{nnnnnnnn} starts at 00000001 and increments each time a new file is created.
A new file is created when the active file reaches a specified size.
All message files other than the active one end with a footer record.
Every record in a message log file contains a header portion and a data portion.
The header portion of each record and the header and footer records are used to manage
message delivery.  The data portion of a message record contains the application message to be delivered.
An application message may be text or binary data.

@item @code{@i{name}.cursor}
@tab A cursor file points to an offset within a numbered message file.
Cursor files may be used by processes that read a message log and need to keep track of their position within the log.
A cursor file is not required by processes that maintain state in some other way.

@item @code{~.socket}
@tab Each message log has a single "producer"---a process that writes to the log. 
A producer file is a local domain socket that can be used by "consumers" (processes that read from the log) to request a stream of new messages via UDP packets. 

@item @code{@i{name}.socket}
@tab A consumer file is a local domain socket used for sending messages via UDP packets from the producer to a consumer.
@end multitable


@section Producer and Consumer
@cindex producer
@cindex consumer

A message producer is a component that writes to a message log.
A message consumer is a component that reads from a message log.
Consumers keep track of their position within the message log by updating a cursor file.
A consumer may receive messages by polling the message log for new messages or by requesting that the producer provide a stream of new messages via UDP.

A consumer that requests a UDP stream of messages doesn't have to read the message log, unless a missed packet is detected.
The UDP packets are numbered to enable the detection of a missed packet and include the offset
within the message log where the next message will be stored.  This enables the message server
to start reading directly at the message contained in a missed packet.

The goal of this design is to ensure rapid delivery when both the producer and server
are running efficiently, but also to decouple the producer and server so either one can operate without the other,
or at different speeds, at any given time. 


@section Server and Client
@cindex server
@cindex client

A message server delivers messages from a message log
to message clients.  A message client is a component that connects to a message server
and requests messages starting at a given state.  While a client maintains a connection to
a message server, messages will continue to stream in near real-time as generated by the message producer.
The connection between a client and server can actually be requested by either the client or the server,
meaning the client and server are peers.

Often a component is both a message client and a message producer, and the component logs messages it
receives from servers as well as messages it originates.
The corresponding message server is then able to serve messages originating at multiple producers.
Because a server is a consumer, the communication between a producer and a server is described in the previous section.
The current design allows for only one server per message log.
This is because a server always uses the node name as the consumer name.


@section Source and Sink
@cindex source
@cindex sink

A message node is a "source" when the producer is not also a client.  
The message log produced by such a node contains only messages it generates.
A message node is a "sink" when it has a client but no server.
A client of a "sink" node may replicate received messages, in which case it is a producer and may have consumers.
The use of source and sink nodes is appropriate in cases where you simply want to collect messages from one or more
nodes and process the messages at one or more other nodes.


@section Cabals, Node Numbers, and State
@cindex cabals
@cindex node numbers
@cindex state

A message cabal is a set of nodes sharing messages for some purpose.
The message log of every node with a server is assigned a number from 1 to 255, which means there can be at most 255 nodes with servers in a cabal.
All nodes without servers may share a common node number of 0.
Each client is required to maintain a state, which is defined as a set of the last message identifier received from each server.
A client's state is passed to a message server when a connection is established, enabling the server to only
deliver messages the client is not known to have already received.


@section Adaptive Ring, Hub, and Spoke Topology
@cindex adaptive topology
@cindex ring
@cindex hub
@cindex spoke

Each node within a cabal has a strategy for maintaining connections with other nodes.
This strategy depends on the type of node.
@multitable {--------------------} {--------------------------------------------------------------------------------------}
@item @b{Type} @w{            } @tab @b{Strategy}
@item source server @tab accept connections from sink clients
@item sink client   @tab request connections to all source servers
@item hub server  @tab accept connections from hub and spoke clients, request connection to preferred hub client
@item hub client  @tab accept connections from hub servers, request connection to preferred hub server
@item spoke client  @tab request connection to preferred hub server
@end multitable

Sink and source nodes use a one-directional, many-to-many topology.  Hub nodes form a ring topology, enabling efficient and scalable
message broadcasting to all nodes.  Spoke nodes are able to tap into any hub node, enabling access to all broadcast messages without
having to be a conduit for the ring.

For hub and spoke nodes, an ordered list of all cabal nodes specifies the preferred connections: @i{node1},@i{node2},...,@i{nodeN}.
This list is circular, so @i{node1} follows @i{nodeN}.  
A hub server prefers connecting to the first hub client following it in the circular list.
If the connection fails, it continues through the list until a connection to a hub client is made, or there are no more hub clients (reached self in list).  A hub client prefers connecting to the first hub server prior to it in the circular list.  Like a server, it continues through the list (only backwards) until a connection succeeds or there are no more hub servers (wrapped around to self).  Spoke clients use the same strategy as hub clients to search the list backwards for the first hub for which a connection succeeds.  Sink clients search the list and attempt to connect to every source server.

The most interesting connections are those between hub clients and hub servers.  These can be requested and accepted by both clients and servers. So using the terms "client" and "server" is a bit awkward.  If you think of hub nodes as peers, they each want a connection to the first hub node ahead and behind themselves in the circular list, forming a ring.  
If a given node is down or unreachable it is bypassed and a smaller ring is formed. 

When a node does not have a preferred set of connections, it periodically attempts to establish a preferred set of connections.
Once a preferred connection is established, an alternate connection requested by the node is dropped.  
Extra connections requested by peers are maintained until the peers decide to drop them.  In other words, the node that requests a connection is responsible for deciding when it is no longer needed.

This strategy enables replication on broadcast rings to adapt to network or system problems.
For example, if a set of five nodes in a ring of ten nodes becomes isolated from the other five because of a network problem, both sets of five will form into separate rings.  When the network problem is resolved, the larger ten-node ring will form again.

@section Delivery Sequence
@cindex delivery
@cindex sequence

Messages originating at any given node are delivered in sequence, once and only once, to every subscribing node.  By "delivery," we mean complete delivery.  In a scenario where a ring adapts to a problem and is in the process of repairing itself, it is possible to have redundant transport, or partial delivery, of a message within the messaging layer. 
However, only messages not yet received will make it through final delivery to the application layer.

Messages originating on two different nodes can arrive at a third node in any order.  Let's say node A and node B are originating messages and node C subscribes to both.  Messages from A will arrive in order at C, once and only once.  Messages from B will arrive in order at C, once and only once.  However, a message A1 originating at node A before a message B2 originates at B, may arrive at C before or after B2.  It is like shuffling a deck of cards with a stack from A in the left hand and a stack from B in the right hand.  The cards from a given hand stay in order, but there are many ways the two stacks might merge.

@section Conflict Resolution
@cindex conflict resolution

When using the NodeBrain Message API to implement multi-master object replication, it is the application's responsibility to perform conflict resolution.  There is no one approach that will work for all applications.  However, there is a general approach that will work for many applications.

@itemize @bullet
@item Assign a unique identifier to each object.
@item Assign a unique instance number to each object store where updates originate.
@item Include an instance attribute for every object.  This identifies the instance that originated the last update.
@item Include a version number attribute for every object. 
@item Include an update time stamp attribute for every object.  This not required, but nice to have.
@item When an object is added or updated, assign the local instance number, increment the version number, stamp the current time, and issue an "assert" transaction message including a complete copy (specification) of the updated object and both the instance number and version number prior to update.
@item When an object is deleted, issue a "delete" transaction message including object identifier, instance, and version.
@item When processing an "assert" transaction message for an object that doesn't already exist, add the object.
@item When processing an "assert" for an existing object and the instance and version are the ones the transaction claims were updated on the original node, then apply the update.  Otherwise, apply the update only if the new instance number is lower than the existing instance number.
@item When processing a "delete" transaction message for an existing object, only delete it when the instance and version in the message match the local copy.
@end itemize

This approach ensures that all instances of the object store remain synchronized over time, although they can be a bit off at any given moment.
This is not the same as saying all object stores will be "correct."  We are only claiming they will be the same.  A simultaneous delete and update on two different object stores will preserve the update and drop the delete at every store.  This seems like a best result for many applications, but for others it might be the wrong result.  Simultaneous updates at two different stores will preserve the update from the lower numbered instance.  This ensures all object stores end up the same, but which update should actually win is not clear.  For a given application, there may be additional factors for making this determination, perhaps a ranking of users initiating the update, or perhaps the updates can be merged to accept both updates.
So the conflict resolution logic must be designed for the application.  The approach outlined above can be used for many applications and can be used as a starting point for designing others.  

@node Tutorial
@chapter Tutorial
@cindex tutorial

This section illustrates the use of the Message module with simple examples.  

bingo. define alert node message.producer("alert","E1",1);

@node Commands
@chapter Commands
@cindex commands

This section describes the syntax and semantics of commands used with the Message module.

@menu
* Define:: 
* Assertions::
* Cell Expressions:: 
* Node Commands:: 
* Module Commands:: 
@end menu
@node Define
@section Define 
@cindex define

This section describes the syntax for defining Message nodes.

@subsection Define Producer
@cindex producer

The @code{message.producer} node is used to write NodeBrain commands to a message log for processing by other members of a message cabal.

@example
define @i{node} node message.producer("@i{cabal}","@i{nodename}",@i{nodenumber})[:@i{option}[,...]];
@end example

@multitable {--------------------} {--------------------------------------------------------------------------------------}
@item @b{Parameter}@w{         }@tab @b{Description}

@item @i{cabal}
@tab Identifies a cabal subdirectory in the message subdirectory of a caboodle (root directory of NodeBrain application).
This is a directory containing message logs for every node in the cabal that run within the application on the local host.

@item @i{nodename} @tab
Identifies a node within the cabal and a message log (directory) within the cabal subdirectory.

@item @i{nodenumber} @tab
The unique node number from 1 to 255 assigned to this message log within a cabal, or 0 for nodes with no server.

@item @b{Option}@tab @b{Description}

@item trace @tab
The @code{trace} option is used to generate log messages for troubleshooting.
@end multitable

@subsection Define Consumer
@cindex consumer
@cindex define

A @code{message.consumer} node is used to read NodeBrain commands from a message log and pass them to the interpreter.

@example
define @i{node} node message.consumer("@i{cabal}","@i{nodename}",@i{nodenumber},"@i{name}")[:@i{option}[,...]];
@end example

@multitable {--------------------} {--------------------------------------------------------------------------------------}
@item @b{Parameter}@w{         }@tab @b{Description}

@item @i{cabal}
@tab Identifies a cabal subdirectory in the message subdirectory of a caboodle (root directory of NodeBrain application).
This is a directory containing message logs for every node in the cabal that run within the application on the local host.

@item @i{nodename} @tab
Identifies a node within the cabal, and a message log (directory) within the cabal subdirectory.

@item @i{nodenumber} @tab
A unique node number from 1 to 255 assigned to this message log within a cabal, or 0 for nodes with no server.

@item @i{name} @tab
This parameter uniquely identifies a consumer.

@item @b{Option}@tab @b{Description}

@item trace @tab
The @code{trace} option is used to generate log messages for troubleshooting.
@end multitable

@subsection Define Server
@cindex server
@cindex define

A @code{message.server} node accepts connections from clients and delivers messages that are
new relative to a client's state.  A state is defined by the last message identifier received by the client from each
non-zero node number within the cabal.

@example
define @i{node} node message.server("@i{cabal}","@i{nodename}")[:@i{option}[,...]];
@end example

@multitable {--------------------} {--------------------------------------------------------------------------------------}
@item @b{Parameter}@w{         }@tab @b{Description}

@item @i{cabal}
@tab Identifies a cabal subdirectory in the message subdirectory of a caboodle (root directory of NodeBrain application).
This is a directory containing message logs for every node in the cabal that run within the application on the local host.
The parameter also identifies a subordinate rule node for cabal configuration.  See "Cabal Configuration" below.

@item @i{nodename} @tab
Identifies a node within the cabal, a message log (directory) within the cabal subdirectory, and subordinate cabal
node configuration rule node.  See "Cabal Configuration."

@item @b{Option}@tab @b{Description}

@item trace @tab
The @code{trace} option is used to generate log messages for troubleshooting.
@end multitable


@subsection Define Client
@cindex client
@cindex define

A @code{message.client} node connects to one or more Message servers and requests a feed of all messages
that are new relative to the client's state.  A state is defined by the last message identifier received for
each producer within the cabal.

@example
define @i{node} node message.client("@i{cabal}","@i{nodename}")[:@i{option}[,...]];
@end example

@multitable {--------------------} {--------------------------------------------------------------------------------------}
@item @b{Parameter}@w{         }@tab @b{Description}

@item @i{cabal}
@tab Identifies a cabal subdirectory in the message subdirectory of a caboodle (root directory of NodeBrain application).
This is a directory containing message logs for every node in the cabal that run within the application on the local host.
The parameter also identifies a subordinate rule node for cabal configuration.
See "Define Server" for a description of cabal configuration.

@item @i{nodename} @tab
Identifies a node within the cabal, a message log (directory) within the cabal subdirectory, and a subordinate rule node
configuring the node within the cabal.  See "Cabal Configuration."

@item @b{Option}@tab @b{Description}

@item trace @tab
The @code{trace} option is used to generate log messages for troubleshooting.
@end multitable


@subsection Cabal Configuration
@cindex cabal

Server and client nodes reference a cabal configuration rule set.
These rules identify all nodes in the cabal and information needed to communicate.

A cabal configuration node identified by the cabal parameter is defined as follows.
@example
define @i{node} node message.@{server|client@}("@i{cabal}","@i{nodeI}")[:@i{option}[,...]];
@i{node}. define @i{cabal} node;
@i{node}.@i{cabal}. source agent/@i{cabal}.nb;
@end example

The @code{agent/@i{cabal}.nb} file looks like this.
@example
define ring cell "@i{node1},...,@i{nodeI},...,@i{nodeN}";
define @i{node1} node;
...
#
define @i{nodeI} node;
@i{nodeI}. define id     cell @i{I};       # instance number (e.g., 3)
@i{nodeI}. define type   cell "hub";   # hub | spoke | source | sink
@i{nodeI}. define client cell "tls://@i{ipaddress}:@i{port}"; # all nodes
@i{nodeI}. define server cell "tls://@i{ipaddress}:@i{port}"; # hub or source only
#
define @i{nodeN} node;
...
@end example

When all nodes are running on the same host, you may specify clients and servers using local domain sockets as @code{"unix://@i{path}"}.
If security is not an issue, you may also replace "tls" with "tcp" for remote clients and servers.
In all cases, it is important to use identical cabal configuration files for every node in the cabal.
The client and server entries for a given node tell it how to listen for connections as well as telling every other node how to connect.


@node Assertions
@section Assertions
@cindex assertions
@cindex assert
@cindex alert

The Message module does not implement the @code{assert} and @code{alert} commands.

@node Cell Expressions
@section Cell Expressions
@cindex cells
@cindex evaluation

The Message module does not implement cell evaluation.

@node Node Commands
@section Node Commands
@cindex node commands

This section describes commands implemented by the Message module for use with defined nodes.

@subsection Trace
@cindex trace

The @code{trace} command is used to toggle the @code{trace} option for troubleshooting.
@example
@i{node}:trace [on|off]
@end example

@node Module Commands
@section Module Commands
@cindex module commands

The Message module provides commands for managing message logs.  These commands are registered with the
command interpreter so they may be invoked without first defining a node.  These commands start with @code{message}
followed by a period and then a verb.

@example
message.@i{verb} @i{body}
@end example

@subsection Create
@cindex create command

The @code{message.create} command is used to initialize a message log before using for the first time with a message node.

@example
message.create [@i{path}] @i{cabal} @i{nodename} @i{nodenumber} [@i{type}]
@end example

@multitable {--------------------} {--------------------------------------------------------------------------------------}
@item @b{Element}@w{         }@tab @b{Description}

@item @i{path}
@tab Specifies a path to a directory containing message logs.  
When specified, a path must start with "/" or "./". 
A path starting with "./" is relative to the working directory. 
The default value is "./message", which assumes the command is executed with a NodeBrain caboodle as the working directory and message logs are stored in this directory.

@item @i{cabal}
@tab The name of the cabal in which the new message log will participate.

@item @i{nodename}
@tab The name of the node for which a new message log is requested.

@item @i{nodenumber}
@tab Number from 0 to 255 assigned to the specified node within the specified cabal.  This number may be zero for a spoke or sink node, but must otherwise be a unique number within the cabal greater than zero.  The @code{create} command is not aware of the numbers that may have been assigned to other nodes, perhaps on other machines, so you must manually reference a common cabal configuration file to make this assignment properly.

@item @i{type}
@tab When the @i{nodenumber} is zero (a message log with no server), specify @code{content} if you want messages logged, or @code{state} to simply maintain a node's message state.  
When @code{state} is specified, the state is stored as a message log file header record and updated as each message arrives.
This option may be used by "sink" and "spoke" client nodes to keep track of their state without using up file space to store messages.  
There are times where it is desirable to store message content at "sink" and "spoke" client nodes for visibility or for sharing with local consumer nodes.
When the @i{nodenumber} is non-zero, the @i{type} may be omitted, or a value of @code{content} may be specified.
A value of @code{state} is not allowed with a non-zero @i{nodenumber}.

@itemize @bullet
@item @code{content} - Write messages to the log.
@item @code{state} - Only maintain a state (header) record.
@end itemize
@end multitable

When the @code{content} option is specified, or used by default, a numbered message file is created with a named symbolic link.
The numbered message file is initialized with a header record.

@example
@i{path}/@i{cabal}/@i{nodename}/@i{nodename}.msg -> 00000001.msg    
@i{path}/@i{cabal}/@i{nodename}/00000001.msg
@end example

When the @code{state} option is specified, the named message file is created as a regular file with a header record.
The content of the named file is the same as the numbered file created under the @code{content} option.

@example
@i{path}/@i{cabal}/@i{nodename}/@i{nodename}.msg
@end example

In either case, the named message file can be read to determine the state of the message log.

@subsection Export
@cindex export command

The @code{export} command is used to convert a message log file into text.
This may be useful for troubleshooting.
In the future, we anticipate providing a corresponding @code{import} command,
which would enable repairs to corrupted log files using a text editor.

@example
message.export [@i{path}] @i{cabal} @i{nodename} @i{nodenumber} @i{filename}
@end example

@multitable {--------------------} {--------------------------------------------------------------------------------------}
@item @b{Element}@w{         }@tab @b{Description}

@item @i{path}
@tab Specifies a path to a directory containing message logs.
When specified, a path must start with "/" or "./".  The default path is "./message".

@item @i{cabal}
@tab Specify the name of the cabal in which the message log participates.

@item @i{nodename}
@tab Specify the name of the cabal node.

@item @i{nodenumber}
@tab Number from 0 to 255 assigned to the specified node within the specified cabal.
The @i{nodenumber} parameters is currently required by the NodeBrain Message API for validation.
If the specified @i{filename} is not for the specified @i{nodenumber}, an error is displayed and the file is not exported.
While this validation is appropriate for other uses of the Message API, a future enhancement to the
API may enable the @code{export} command to work without requiring the @i{nodenumber}.

@item @i{filename}
@tab Specify the name of the message file to export. The file name is of the form @code{@i{nodename}.msg} or @code{@i{nnnnnnnn}.msg}. 
@end multitable

The full path to the message log exported is shown below.

@example
@i{path}/@i{cabal}/@i{nodename}/@i{filename}
@end example

@subsection Prune
@cindex prune command

The @code{prune} command is used to retire message files older than specified time period.

@example
message.prune [@i{path}] @i{cabal} @i{nodename} @i{nodenumber} @i{retention}
@end example

@multitable {--------------------} {--------------------------------------------------------------------------------------}
@item @b{Element}@w{         }@tab @b{Description}

@item @i{path}
@tab Specifies a path to a directory containing message logs.
When specified, a path must start with "/" or "./".  The default path is "./message".

@item @i{cabal}
@tab Specify the name of the cabal in which the message log participates.

@item @i{nodename}
@tab Specify the name of the cabal node.

@item @i{nodenumber}
@tab Number from 0 to 255 assigned to the specified node within the specified cabal.
The @i{nodenumber} parameters is currently required by the NodeBrain Message API for validation.
If the specified @i{filename} is not for the specified @i{nodenumber}, an error is displayed and the log is not pruned.
While this validation is appropriate for other uses of the Message API, a future enhancement to the
API may enable the @code{prune} command to work without requiring the @i{nodenumber}.

@item @i{retension}
@tab Specify a number @i{n} followed by a letter identifying the time unit: (d)ay, (h)our, (m)inute, (s) second.
For example, @code{20d} specifies a retention of 20 days.
@end multitable

@node Triggers
@chapter Triggers
@cindex triggers

A @code{message.client} node passes all commands received from a @code{message.server} to the interpreter.
There are no other trigger conditions implemented by the Message module.
A future enhancement may provide an option for @code{message.server} nodes to generate connection status change alerts,
enabling rules to respond.

@node GNU Free Documentation License
@unnumbered GNU Free Documentation License
@include fdl.texi

@node Index
@unnumbered Index
@printindex cp

@bye
