\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename nb_webster.info
@include version.texi
@settitle Webster NodeBrain Module
@c %**end of header

@finalout
@paragraphindent none
@setchapternewpage odd

@copying
Webster NodeBrain Module@*
July 2014*
NodeBrain Open Soure Project

@sp 2
@b{Release @value{RELEASE}}

Author: Ed Trettevik

Copyright @copyright{} 2014 Ed Trettevik <eat@@nodebrain.org>

@sp 1
Permission is granted to copy, distribute and/or modify this document under the terms of either the MIT License (Expat) or the NodeBrain License.
@sp 1
@include ../../../doc/licenses.texi
@end copying

@iftex
@titlepage
@c @image{./image001,32pt,32pt,,gif}

@titlefont{Webster NodeBrain Module}
@sp 1
@tex
\vskip4pt \hrule height 3pt width \hsize
@end tex
@sp 3
@b{Release @value{RELEASE}}
@page
@vskip 0pt plus 1filll
@insertcopying

@c History Preface and Document Conventions 
@page
@b{History}

@multitable {-------------} {--------------------------------------------------------------------------------------------------------}
@item 2005-10-12 @tab
Title: @i{NodeBrain Tutorial}@*
Author: Ed Trettevik <eat@@nodebrain.org>@*
Publisher: NodeBrain Open Source Project

@item 2010-12-31 @tab
Release 0.8.3
@itemize @bullet
@item Updates - still needed
@end itemize

@end multitable

@page
@b{Preface}

@sp 1
This module is intended for readers seeking an introduction to NodeBrain through a series of simple examples. Other documents are available for readers looking for a more complete reference to the rule language, modules, or API (application programmatic interface).

The intent of the examples in this module is to illustrate individual concepts, not to provide complete working applications or show all related options.
We avoid formal syntax descriptions, thinking you are here because you want to figure it out from examples.  

Files referenced in this tutorial are included in the tutorial directory of the NodeBrain distribution.  

See www.nodebrain.org for more information and the latest update to this document.

@include conventions.texi

@end titlepage

@end iftex

@c ----------------------------------------------------------
@c Not printed document

@ifnottex
@node Top
@top Webster NodeBrain Module

This manual is for the Webster NodeBrain Module (version @value{VERSION}, @value{UPDATED-MONTH}) used as minimal web server for a NodeBrain application.
@*
Copyright @copyright{} 2014 Ed Trettevik
@quotation
Permission is granted to copy, distribute and/or modify this document under the terms of either the MIT License (Expat) or NodeBrain License.
See the @i{Licenses} section at the end of this document for details.
@end quotation

@ifnotplaintext
@b{Short Table of Contents}
@end ifnotplaintext
@menu
* Concepts:: Foundation
* Tutorial:: Introduction by Example
* Commands:: Syntax and Semantics
* Triggers:: Conditions and Response
@end menu
@menu
* Licenses::
* Index::
@end menu
@end ifnottex

@c Set page footings
@oddfooting @thistitle @| @| @thispage
@evenfooting @thispage @| @| @thistitle

@c Contents
@oddheading @| @| 
@evenheading @| @|
@contents

@c Set page headings for document
@oddheading @thischapter @| @| @value{UPDATED-MONTH}
@evenheading @value{UPDATED-MONTH} @| @| @thischapter


@node Concepts
@chapter Concepts
@cindex concepts

A Webster module provides administrators with an HTTPS interface to NodeBrain agents, enabling the use of a web browser as a client. It is not intended as a general purpose web server and should not be used as alternative to web servers like Apache that are designed for general purpose use. However, it can be used to provide access to custom content packaged with a NodeBrain kit or application where a low rate of access is expected.  

@node Tutorial
@chapter Tutorial
@cindex tutorial
@include nb_webster_tutorial.texi

@node Commands
@chapter Commands
@cindex commands

@section Define
@cindex define command
 
@cartouche
@b{Syntax}
@multitable {-----------------------------} {----------------------------------------------------------------}	   
@item @i{websterDefinition} @tab ::= @b{define} @ringaccent{s} @i{term} @ringaccent{s} @b{node} [@ringaccent{s} @b{"} @i{identity} @b{"} ] [;] @bullet{} 	   
@item @i{identity}          @tab ::= Identity for commands issued by the webster node.
@item @i{cellOption}        @tab ::= @i{term}. define @i{option} @b{cell} @i{value} [;] @bullet{}
@item @i{textOption}        @tab ::= @i{term}. define @i{websterModuleOption} @b{text:} @i{value} @bullet{}
@item @i{option}            @tab ::= @i{tlsApiOption} | @i{websterApiOption} | @i{websterModuleOption}
@item @i{tlsApiOption}      @tab ::= See list below
@item @i{websterApiOption}  @tab ::= See list below
@item @i{websterModuleOption} @tab ::= See list below
@end multitable			 
@end cartouche

The following NodeBrain TLS API options are specified as cells within the context of a Webster node.
@multitable {------------------------} {------------------------------------------------------------------------}
@item @b{Option}           @tab @b{Description}	   
@item uri                  @tab Protocol, interface, and port
@item                      @tab Default: "https://0.0.0.0:49443"
@item option               @tab Authentication option
@item                      @tab Default: "CERTS"
@item timeout              @tab Read timeout seconds
@item                      @tab Default: 5
@item keyfile              @tab File containing the server key
@item                      @tab Default: "security/ServerKey.pem"
@item certfile             @tab File containing the server certificate
@item                      @tab Default: "security/ServerCert.pem"
@item trustfile            @tab File containing the server key
@item                      @tab Default: "security/TrustedCertificates.pem"
@end multitable

The following NodeBrain Webster API options are specified as cells within the context of a Webster node.
@multitable {------------------------} {------------------------------------------------------------------------}
@item @b{Option}           @tab @b{Description}
@item Filter               @tab NodeBrain translator used as web application filter
@item                      @tab Define: -none-
@item DocumentRoot         @tab Root directory for web pages
@item                      @tab Default: "web"	   
@item IndexPage            @tab Page selected by default when resource is a directory
@item                      @tab Default: "index.html"
@item IndexQuery           @tab Parameters if the IndexPage accepts them (e.g. cgi script)
@item                      @tab Default: -none-
@item Authenticate         @tab Authentication option "yes" | "certificate" | "password" | "no"
@item                      @tab Default: "yes"
@item AccessList           @tab Access control list file [deprecated - see Authorize]
@item                      @tab Default: "security/AccessList.conf"
@item Config               @tab Configuration file name - see next block of options below
@item                      @tab Default: ""
@end multitable

The following Webster module options are specified as string or text cells within the context of a Webster node.

@multitable {------------------------} {------------------------------------------------------------------------}
@item @b{Option}           @tab @b{Description}
@item Title                @tab Title displayed in the center of a Webster page heading
@item                      @tab Default: "MyCaboodle"
@item Link                 @tab Link associated with the title in Webster page heading
@item                      @tab Default: "http://nodebrain.org"
@item Menu                 @tab Menu displayed in top right area of Webster page heading
@item                      @tab Default: "<a href=':page'>Webster</a>"
@item Version              @tab Application version number to display in Webster page heading
@item                      @tab Default: ""
@end multitable

When Webster module options are specified in a configuration file identified by the @code{Config} option and
illustrated below, the values
specified in the configuration file override values specified as cells. 

@cartouche
@smallexample
# Comment lines start with "#".
# Blank lines are allowed
Title="MyCaboodle";
Version="";
Link="http://nodebrain.org";
Menu="<a href=':page">Webster</a>";
@end smallexample
@end cartouche

One reason you want to use a configuration file is to share these options with cgi scripts.

@node Triggers
@chapter Triggers
@cindex triggers 

The Webster module does not implement any triggers

@ifnottex
@node Licenses
@unnumbered Licenses

NodeBrain is free software; you can modify and/or redistribute it, including this document, under the
terms of either the MIT License (Expat) or the NodeBrain License.

@sp 1
@include ../../../doc/licenses.texi
@end ifnottex

@node Index 
@unnumbered Index 
@printindex cp 
@bye 
