## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.
     
nblib_LTLIBRARIES = nb_baseline.la
nb_baseline_la_SOURCES = nb_baseline.c
nb_baseline_la_CFLAGS  = $(NB_INCLUDE)
nb_baseline_la_LDFLAGS = -module -version-info 0:4

EXTRA_DIST = \
  caboodle/check/baseline.nb~ \
  caboodle/cache/baseline/test/README \
  doc/baseline.texi \
  doc/version.texi 
