#!/usr/bin/perl
#
# File:    texi4pdf
#
# Title:   Texinfo translation for input to texi2pdf
#
# Purpose:
#
#   This script is used to make some translations to NodeBrain
#   texinfo (*.texi) files prior to executing texi2pdf.
#
# Description:
#
#   We are using a "preprocessor" approach here because we were
#   unsuccessful in getting a macro like the following to work.
#
#      @iftex                 @iftex
#      @macro myexample       @macro myendexample
#      @cartouche             @end group
#      @smallformat           @end smallformat
#      @group                 @end group
#      @end macro             @end macro
#
#   For some reason, texi2pdf has problems when each @-command
#   is not @end'd before the @end macro.
#
#   We replace the @example macro as shown below to provide
#   better results in a printed document.
#
#      @example           @cartouche
#                         @smallformat
#                         @group
#      ...                ...
#                         @end group
#                         @end smallformat
#      @end example       @end cartouche
#
#=================================================================
# Change History:
#
# Date       Name/Description
# ---------- -----------------------------------------------------
# 2009-03-04 Ed Trettevik
#=================================================================
while(<>){
  if(/^\@example/){print("\@cartouche\n\@smallexample\n");}
  elsif(/^\@end example/){print("\@end smallexample\n\@end cartouche\n");}
  else{print;}
  }
