\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename nodebrain.info
@include version-nodebrain.texi
@settitle NodeBrain Documents
@dircategory NodeBrain
@direntry
* NodeBrain: (nodebrain).	State and Event Monitoring Agent
* nb: (nodebrain)Command.	NodeBrain command
@end direntry
@c %**end of header

@node Top
NodeBrain is a program for monitoring state and events.
@ifinfo
@inforef{Top,fun,nbTutorial.info}

@inforef{Top,fun,nbLanguage.info}
@end ifinfo
