## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_console.la
nb_console_la_SOURCES = nb_console.c
nb_console_la_CFLAGS  = $(NB_INCLUDE)
nb_console_la_LDFLAGS = -module -version-info 0:1

EXTRA_DIST = \
  caboodle/check/console.nb~
