\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename nb_servant.info
@include version.texi
@settitle Servant NodeBrain Module
@c %**end of header

@finalout
@paragraphindent none
@setchapternewpage odd

@copying
Servant NodeBrain Module@*
June 2014@*
NodeBrain Open Source Project

@sp 2
@b{Release 0.8}

Author: Ed Trettevik <eat@@nodebrain.org>

Copyright @copyright{} 2006--2014 Ed Trettevik <eat@@nodebrain.org>

@sp 1
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or any later version published by the Free Software Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included in the section titled @i{GNU Free Documentation License} at the end of this document.

@sp 1
All trademarks and registered trademarks referenced in this document are the trademarks of their respective owners.

@sp 2
@b{Software License}

Copyright @copyright{} 1998--2014 Ed Trettevik <eat@@nodebrain.org>

NodeBrain is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option)any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License formore details.

You should have received a copy of the GNU General PublicLicense along with this program; if not, write to Free Software Foundation,Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
@end copying

@iftex
@titlepage
@c @image{./image001,32pt,32pt,,gif}

@titlefont{Servant NodeBrain Module}
@sp 1
@tex
\vskip4pt \hrule height 3pt width \hsize
@end tex
@sp 3
@b{Version @value{VERSION}}
@page
@vskip 0pt plus 1filll
@insertcopying

@c History Preface and Document Conventions 
@page
@b{History}

@multitable {-------------} {--------------------------------------------------------------------------------------------------------}
@item 2005-10-12 @tab
Title: @i{Servant NodeBrain Module}@*
Author: Ed Trettevik <eat@@nodebrain.org>@*
Publisher: NodeBrain Open Source Project

@item 2010-12-31 @tab
Release 0.8.10
@itemize @bullet
@item Updates - still needed
@end itemize

@end multitable

@page
@b{Preface}

@sp 1
This tutorial is intended for readers seeking an introduction to NodeBrain through a series of simple examples. Other documents are available for readers looking for a more complete reference to the rule language, modules, or API (application programmatic interface).

The intent of the examples in this tutorial is to illustrate individual concepts, not to provide complete working applications or show all related options.
We avoid formal syntax descriptions, thinking you are here because you want to figure it out from examples.  

Files referenced in this tutorial are included in the tutorial directory of the NodeBrain distribution.  

See www.nodebrain.org for more information and the latest update to this document.

@sp 2
@b{Documents}
@sp 1
@quotation
@i{NodeBrain Tutorial}

@i{NodeBrain User Guide}

@i{NodeBrain Language Reference}

@i{NodeBrain Module Reference}

@i{NodeBrain API Reference}
@end quotation

@sp 2
@b{Document Conventions}
@sp 1
Sample code and input/output examples are displayed in a monospace font, indented in HTML and Info, and enclosed in a box in PDF or printed copies.
Bold text is used to bring the reader's attention to specific portions of an example.
In the following example, the first and last line are associated with the host shell and the lines in between are input or output unique to NodeBrain.
The @code{define} command is highlighted, indicating it is the focus of the example.
Lines starting with "@dots{}" are a continuation of the previous line ending with "@dots{}".
This is not part of the language, just one way of breaking up single lines to fit on a printed page.
If you copy an example, you must remove the dots and combine the lines into a single line.

@cartouche
@smallexample
$ nb
> @b{define myFirstRule on(a=1 and b=2) mood="happy";}
> assert mood="sad";
> show mood
mood = "sad"
> assert a=1,b=2,c=3,d="This is an example of a long single line that", @dots{}
@dots{} e="we depict on multiple lines to fit on the documnet page";
2008/06/05 12:09:08 NB000I Rule myFirstRule fired(mood="happy")
> show mood
mood = "happy"
> quit
$
@end smallexample
@end cartouche

@end titlepage

@end iftex

@c ----------------------------------------------------------
@c Not printed document

@ifnottex
@node Top
@top Servant NodeBrain Module
This manual is for the Servant NodeBrain Module (version @value{VERSION}, @value{UPDATED-MONTH}) used to integrate a NodeBrain agent with other programs that run as child processes. 
@*@*
Copyright @copyright{} 2012-2014 Ed Trettevik <eat@@nodebrain.org>

@quotation
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or any later version published by the Free Software Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included in the section titled @i{GNU Free Documentation License} at the end of this document.
@end quotation

@ifnotplaintext
@b{Short Table of Contents}
@end ifnotplaintext
@menu
* Concepts:: Foundation
* Tutorial:: Introduction by Example
* Commands:: Syntax and Semantics
* Triggers:: Conditions and Response
* GNU Free Documentation License::
* Index::
@end menu
@end ifnottex

@c Set page footings
@oddfooting @thistitle @| @| @thispage
@evenfooting @thispage @| @| @thistitle

@c Contents
@oddheading @| @| 
@evenheading @| @|
@contents

@c Set page headings for document
@oddheading @thischapter @| @| @value{UPDATED-MONTH}
@evenheading @value{UPDATED-MONTH} @| @| @thischapter

@node Concepts
@chapter Concepts
@cindex concepts

In NodeBrain terminology, a servant is a shell command executed as a child process to NodeBrain.  A servant may communicate with NodeBrain via the servant's @code{stdin} and @code{stdout}.
Servants makes it easy for programmers to develop in their favorite programming languages when interfacing to NodeBrain rules. Scripting languages like Perl are convenient for creating servants. You should only consider writing new NodeBrain modules when a problem cannot be solved as well by writing a servant.

@section Servant Command
@cindex servant command

A servant command ("-" or "=") is a convenient may to execute a shell command as a child process.  The command may perform a function that does not require communication with NodeBrain, or it may return commands and log messages for NodeBrain to process. 
See the @i{NodeBrain Language Reference} for the syntax of servant commands ("-" and "=").

@section Servant Node
@cindex servant node

A servant node, implemented by the Servant module, is also used to execute a shell command as a child process.
But a servant node is different than a servant command in the following ways.

@enumerate
@item Rules can send messages to a servant node on the servant's @code{stdin} in addition to accepting commands on the servant's @code{stdout}.

@item Servant nodes are not enabled (spawned) until NodeBrain enters a server mode. This is necessary in the case of daemons (-d) because the NodeBrain process terminates when it spawns itself as a daemon. Any processes started before entering daemon mode are orphaned and no longer able to communicate on @code{stdin} or @code{stdout}. This is also helpful for other server modes (e.g., servant) because it enables all the startup rules to be fully defined before a servant starts generating commands.

@item In a future release you will be able to use the @code{enable} and @code{disable} commands to start and stop servant nodes.
This is possible because they have a term (name) that can be used as a reference. The servant command ("-" or "=") only identifies a servant by process ID (PID), and although the PID is displayed and can be referenced in shell commands like @code{kill}, the PID is not captured in a way that NodeBrain rules can reference.
@end enumerate

@section NodeBrain as Servant
@cindex NodeBrain as Servant

A servant node can run NodeBrain (nb) in a new process the same way it runs other servant programs and scripts. The servant module's support for two-way message communication between processes enables a NodeBrain application to be divided into multiple processes. When you define a servant that executes NodeBrain, messages sent to @code{stdin} and received from @code{stdout} are all NodeBrain commands. This allows the processes to share information and make decisions or take actions as a service to each other.

When NodeBrain is run as a servant to another NodeBrain process, use the -s (servant) option if you want the child to run as a server. Use the "=" option instead if you want the child to operate in batch mode.

The @i{NodeBrain Language Reference} provides a description of NodeBrain options and the full syntax of the servant command ("-" or "="), which is key to understanding the syntax used by the servant module.

@node Tutorial
@chapter Tutorial
@cindex tutorial
@include nb_servant_tutorial.texi

@node Commands
@chapter Commands
@cindex commands

This section describes the syntax and semantics of commands used with the Servant module.

@section Define
@cindex define command

A servant is defined as a node, where the foreign text includes the full syntax of a servant command ("-" or "=").
 
@cartouche
@b{Syntax}
@multitable {----------------------} {-----------------------------------------------------------------------} 
@item @i{servantDefinition} @tab ::= @b{define} @v{s} @i{term} @v{s} @b{node} [@v{s} @i{servantSpec} ] @bullet{} 	   
@item @i{servantSpec}       @tab ::= @b{servant} [ @b{(} @i{servantOptions} @b{(} ]  @b{:} [ @b{|} ] @i{servantCmd}	   
@item @i{servantOptions}    @tab ::= there are currently no options defined for this module	   
@item @i{servantCmd}        @tab ::= see "-" and "=" command in the @i{NodeBrain Language Reference}	   
@end multitable		 
@end cartouche

@section Node Commands
@cindex node commands

Once NodeBrain is running in a server mode (e.g., agent/daemon/service or servant), you may pass messages to a servant using a node command. Suppose you define a Perl script named @code{servant.pl} as a servant named @i{servant}.

@cartouche
@smallexample
define servant node servant:|=:./servant.pl
@end smallexample
@end cartouche


Once in server mode, you can pass a message to @code{servant.pl} on @code{stdin} as follows.

@cartouche
@smallexample
servant:@i{message}
@end smallexample
@end cartouche

This is how you pass messages to any node. In this case, the servant node module simply forwards all messages to the specified servant program on @code{stdin}.

@node Triggers
@chapter Triggers
@cindex triggers

There are no triggers provided by the Servant module directly.
It is entirely up to the servant program to determine what commands are sent to NodeBrain and the conditions that trigger them.
Output from a servant may be interpreted as NodeBrain commands in the servant's context.
This is no different than receiving messages from a servant command ("-:" or "=:"). In both cases, the messages are interpreted as NodeBrain commands within the context in which they are specified.
@*@*
Let's look at a trivial example. Suppose the @code{servant.pl} looks like this.

@cartouche
@smallexample
#!/usr/bin/perl
use FileHandle;
STDOUT->autoflush(1);  # flush stdout as soon as we write to it
while(<>)@{
   if(/^on$/)@{print("assert status;\n");@}
   elsif(/^off$/)@{print(“assert !status;\n”);@}
   else@{print("assert ?status;\n");@}
   @}  
@end smallexample
@end cartouche

Now let's define the following NodeBrain daemon script and call it @code{servant.nb}.

@cartouche
@smallexample
#!/usr/local/bin/nb -d
set log="servant.log";
-cp /dev/null servant.txt
define taylor   node servant:=:tail -f servant.txt
define servant node servant:|=:./servant.pl
servant. define hello on(.status):-echo "hi"
@end smallexample
@end cartouche

The following commands will cause the daemon to echo "hi" to the log file twice.

@cartouche
@smallexample
$ ./servant.nb
$ echo "servant:on" >> servant.txt
$ echo "servant:off" >> servant.txt
$ echo "servant:on" >> servant.txt
@end smallexample
@end cartouche

The servant named "taylor" uses the @code{tail} command to input anything you write to @code{servant.txt}. You emptied it out in the line before the servant definition to prevent @code{tail} from giving you old commands from a previous session. When you echo the NodeBrain command (e.g., "servant:on") to @code{servant.txt}, @code{tail} sends them to the servant node module, which passes them on to the NodeBrain interpreter. These commands happen to address the second servant, the one executing the @code{servant.pl} script. The values of "on," "off," and "on" are sent to this script on @code{stdin}. The @code{servant.pl} script simply translates these messages into NodeBrain commands that set a value for the "status" term. When status is set to 1, the "hello" rule fires.

Obviously the @code{servant.pl} script in this example isn't giving you any information you don't already know, so it is of little or no value. You could have just echoed "servant.status=1;" to @code{servant.txt} in place of "servant:on." But the goal here is just to illustrate the servant interface. It should not be difficult to imagine more realistic situations where you send messages to a servant instructing it when to provide information or what information to provide. For example, the servant could check to see whether a process is running or how much space is available in a file system. Servants just need to know how to perform a function or get some information. The NodeBrain rules decide how to respond to the information provided and when specific actions are appropriate.

@node GNU Free Documentation License
@unnumbered GNU Free Documentation License
@include fdl.texi

@node Index 
@unnumbered Index 
@printindex cp 
@bye 
