## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_servant.la
nb_servant_la_SOURCES = nb_servant.c
nb_servant_la_CFLAGS  = $(NB_MOD_CFLAGS)
nb_servant_la_LDFLAGS = -module -version-info 0:1

EXTRA_DIST = \
  caboodle/check/self.nb- \
  caboodle/check/servant.nb~ \
  caboodle/servant/echo.sh
