## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_snmptrap.la
nb_snmptrap_la_SOURCES = nb_snmptrap.c
nb_snmptrap_la_CFLAGS  = $(NB_MOD_CFLAGS)
nb_snmptrap_la_LDFLAGS = -module -version-info 0:1

EXTRA_DIST = \
  caboodle/check/snmptrap.nb~ \
  doc/nb_snmptrap.texi \
  doc/nb_snmptrap_tutorial.texi \
  doc/version.texi
