## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_toy.la
nb_toy_la_SOURCES = nb_toy.c
nb_toy_la_CFLAGS  = $(NB_MOD_CFLAGS)
#nb_toy_la_LDFLAGS = -module -version-info 0:1
nb_toy_la_LDFLAGS = -module -avoid-version -L../../lib/.libs -lnb

EXTRA_DIST = \
  caboodle/check/toy.nb~ \
  doc/makedoc \
  doc/nb_toy.texi \
  doc/conventions.texi \
  doc/version.texi
