## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_cache.la
nb_cache_la_SOURCES = nb_cache.c
nb_cache_la_CFLAGS  = $(NB_MOD_CFLAGS)
nb_cache_la_LDFLAGS = -module -version-info 0:1

EXTRA_DIST = \
  caboodle/check/cache.nb~ 
