## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_netflow.la
nb_netflow_la_SOURCES = nb_netflow.c
nb_netflow_la_CFLAGS  = $(NB_MOD_CFLAGS)
nb_netflow_la_LDFLAGS = -module -version-info 0:1

EXTRA_DIST = \
  caboodle/check/netflow.nb~
