## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_message.la
nb_message_la_SOURCES = nb_message.c
nb_message_la_CFLAGS  = $(NB_MOD_CFLAGS)
nb_message_la_LDFLAGS = -module -version-info 0:1

EXTRA_DIST = \
  caboodle/check/message.nb- \
  caboodle/check/message.pl
