\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename nb_mail.info
@include version.texi
@settitle Mail NodeBrain Module
@c %**end of header

@finalout
@paragraphindent none
@setchapternewpage odd

@copying
Mail NodeBrain Module@*
@value{UPDATED-MONTH}@*
NodeBrain Open Source Project

@sp 2
@b{Release @value{RELEASE}}

Author: Ed Trettevik

Copyright @copyright{} 2014 Ed Trettevik <eat@@nodebrain.org>

@sp 1
Permission is granted to copy, distribute and/or modify this document under the terms of either the MIT License (Expat) or the NodeBrain License.
@sp 1
@include ../../../doc/licenses.texi
@end copying

@iftex
@titlepage
@c @image{./image001,32pt,32pt,,gif}

@titlefont{Mail NodeBrain Module}
@sp 1
@tex
\vskip4pt \hrule height 3pt width \hsize
@end tex
@sp 3
@b{Release @value{RELEASE}}
@page
@vskip 0pt plus 1filll
@insertcopying

@c History Preface and Document Conventions 
@page
@b{History}

@multitable {-------------} {--------------------------------------------------------------------------------------------------------}
@item 2005-10-12 @tab
Title: @i{NodeBrain  Tutorial}@*  
Author: Ed  Trettevik <eat@@nodebrain.org>@*
Publisher: NodeBrain Open Source Project

@item 2010-12-31 @tab
Release 0.8.3
@itemize @bullet
@item Updates - still needed
@end itemize

@end multitable

@page
@b{Preface}

@sp 1
This tutorial is intended for readers seeking an introduction to NodeBrain through a series of simple examples.  Other documents are available for readers looking for a more complete reference to the rule language, modules, or API (application programmatic interface).

The intent of the examples in this tutorial is to illustrate individual concepts, not to provide complete working applications or show all related options.
We avoid formal syntax descriptions, thinking you are here because you want to figure it out from examples.  

Files referenced in this tutorial are included in the tutorial directory of the NodeBrain distribution.  

See www.nodebrain.org for more information and the latest update to this document.

@include conventions.texi

@end titlepage

@end iftex

@c ----------------------------------------------------------
@c Not printed document

@ifnottex
@node Top
@top Mail NodeBrain Module

This manual is for the Mail NodeBrain Module (version @value{VERSION}, @value{UPDATED-MONTH}) used to send and receive SMTP mail.
@*@*
Copyright @copyright{} 2014 Ed Trettevik <eat@@nodebrain.org>
@quotation
Permission is granted to copy, distribute and/or modify this document under the terms of either the MIT License (Expat) or NodeBrain License.
See the @i{Licenses} section at the end of this document for details.
@end quotation
@ifnotplaintext
@b{Short Table Of Contents}
@menu
* Concepts:: Foundation
* Tutorial:: Introduction by Example
* Commands:: Syntax and Semantics
* Triggers:: Conditions and Response
@end menu
@menu
* Licenses::
* Index::
@end menu
@end ifnotplaintext
@end ifnottex

@c Set page footings
@oddfooting @thistitle @| @| @thispage
@evenfooting @thispage @| @| @thistitle

@c Contents
@oddheading @| @| 
@evenheading @| @|
@contents

@c Set page headings for document
@oddheading @thischapter @| @| @value{UPDATED-MONTH}
@evenheading @value{UPDATED-MONTH} @| @| @thischapter


@node Concepts
@chapter Concepts	  
@cindex concepts
The mail module accepts SMTP mail messages and stores them in a message queue for handling by the Peer module. See the @i{Peer Module} for information on message queues.

@subsection Disclaimer
@cindex mail module disclaimer
This module will not send mail. We recommend using a servant script to send mail.

Use of this module is not recommended if a standard mail server (e.g., sendmail) is available, which is normally the case. The unusual situation where this module may be helpful is when all of the following are true.

@enumerate

@item You need to collect events from a sensor tool that is able to generate plain text email when conditions of interest are detected, but not capable of delivering alerts via a more convenient method.

@item You don’t want the email delivered from the sensor product to a mail server over the network in plain text.

@item The sensor tool runs on a server without a standard mail server, and for some reason you don’t want to install one.

@item You are able to install NodeBrain on the server hosting the sensor tool. 
@end enumerate

When all these conditions are true, you can configure this module to accept mail at the local host and configure the sensor tool to send email alerts to the local host. Ports other than 25 may be used if supported by your sensor tool. You can process the message queue files locally or use the Peer module for authenticated and encrypted delivery to a remote instance of NodeBrain for processing.

If any of the conditions above are not true, there is probably a better way to collect events from the sensor product. 

@node Tutorial
@chapter Tutorial
@cindex Tutorial

@node Commands
@chapter Commands
@cindex commands

This section describes commands used with the Mail module.

@section Define
@cindex define command
 
@cartouche
@b{Syntax}
@multitable {------------------} {--------------------------------------------------------------------------------} 	   
@item @i{mailDefineCmd}	 @tab ::= @b{define} @v{s} @i{term} @v{s} @b{node} [@v{s} @i{mailReaderDef}] @bullet{} 	   
@item @i{mailReaderDef}	 @tab ::= @b{mail.server(} "@i{socketSpec} " , " @i{qDirectoryPath} " @b{);}	   
@item @i{socketSpec}     @tab ::= [@i{hostname | ipaddress} ]  : @i{port}	   
@item @i{qDirectoryPath} @tab ::= path to message queue directory	   
@end multitable
@end cartouche

The server will only accept mail to usernames that have been declared as identities. See @command{DECLARE IDENTITY} command in the @i{NodeBrain Language Reference}.

@node Triggers
@chapter Triggers
@cindex triggers

The Mail module does not implement any triggers.

@ifnottex
@node Licenses
@unnumbered Licenses

NodeBrain is free software; you can modify and/or redistribute it, including this document, under the
terms of either the MIT License (Expat) or the NodeBrain License.

@sp 1
@include ../../../doc/licenses.texi
@end ifnottex

@node Index 
@unnumbered Index 
@printindex cp 
@bye 
