## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_translator.la
nb_translator_la_SOURCES = nb_translator.c
nb_translator_la_CFLAGS  = $(NB_INCLUDE)
nb_translator_la_LDFLAGS = -module -version-info 0:1

EXTRA_DIST = \
  caboodle/check/translator.nb~ \
  caboodle/plan/translator/translator.nbx  
