## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_audit.la
nb_audit_la_SOURCES = nb_audit.c
nb_audit_la_CFLAGS  = ${NB_MOD_CFLAGS}
nb_audit_la_LDFLAGS = -module -version-info 0:1

EXTRA_DIST = \
  caboodle/check/audit.nb~ \
  caboodle/log/README \
  caboodle/plan/audit/audit.nbx \
  doc/nb_audit.texi \
  doc/nb_audit_tutorial.texi \
  doc/version.texi
