## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_toy.la
nb_toy_la_SOURCES = nb_toy.c
nb_toy_la_CFLAGS  = $(NB_MOD_CFLAGS)
nb_toy_la_LDFLAGS = -module -version-info 0:1

EXTRA_DIST = \
  caboodle/check/toy.nb~
