## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_syslog.la
nb_syslog_la_SOURCES = nb_syslog.c
nb_syslog_la_CFLAGS  = $(NB_MOD_CFLAGS)
nb_syslog_la_LDFLAGS = -module -version-info 0:1

EXTRA_DIST = \
  caboodle/check/syslog.nb~ \
  caboodle/plan/syslog/syslog.nbx
