## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_pipe.la
nb_pipe_la_SOURCES = nb_pipe.c
nb_pipe_la_CFLAGS  = $(NB_MOD_CFLAGS)
nb_pipe_la_LDFLAGS = -module -version-info 0:1

EXTRA_DIST = \
  caboodle/check/pipe.nb~ \
  caboodle/pipe/README \
  caboodle/servant/echo.sh \
  doc/nb_pipe.texi \
  doc/nb_pipe_tutorial.texi \
  doc/version.texi
