## This file, Makefile.nm, provides module specific make rules.  It
## is included by Makefile.am, which you should reference for more
## information.

nblib_LTLIBRARIES = nb_udp.la
nb_udp_la_SOURCES = nb_udp.c
nb_udp_la_CFLAGS  = $(NB_MOD_CFLAGS)
#nb_udp_la_LDFLAGS = -module -version-info 0:1
nb_udp_la_LDFLAGS = -module -avoid-version -L../../lib/.libs -lnb

EXTRA_DIST = \
  caboodle/check/udp.nb-
