\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename nb_snmptrap.info
@include version.texi
@settitle Snmptrap NodeBrain Module
@c %**end of header

@finalout
@paragraphindent none
@setchapternewpage odd

@copying
Snmptrap NodeBrain Module@*
July 2014@*
NodeBrain Open Source Project

@sp 2
@b{Release @value{RELEASE}}

Author: Ed Trettevik <eat@@nodebrain.org>

Copyright @copyright{} 2014 Ed Trettevik <eat@@nodebrain.org>

@sp 1
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or any later version published by the Free Software Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included in the section titled @i{GNU Free Documentation License} at the end of this document.

@sp 1
All trademarks and registered trademarks referenced in this document are the trademarks of their respective owners.

@sp 2
@b{Software License}

Copyright @copyright{} 2014 Ed Trettevik <eat@@nodebrain.org>

The Snmptrap  NodeBrain Module is free software; you can modify and/or redistribute it under the
terms of either the MIT License (Expat) or the following NodeBrain License.

Permission to use and redistribute with or without fee, in source and binary
forms, with or without modification, is granted free of charge to any person
obtaining a copy of this software, provided that the above copyright notice,
this permission notice, and the following disclaimer are retained with source
code and reproduced in documentation included with binary distributions.

Unless required by applicable law or agreed to in writing, this software is
distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.
@end copying

@iftex
@titlepage
@c @image{./image001,32pt,32pt,,gif}

@titlefont{Snmptrap Nodebrain Module}
@sp 1
@tex
\vskip4pt \hrule height 3pt width \hsize
@end tex
@sp 3
@b{Version @value{VERSION}}
@page
@vskip 0pt plus 1filll
@insertcopying

@c History Preface and Document Conventions 
@page
@b{History}

@multitable {-------------} {--------------------------------------------------------------------------------------------------------}
@item 2005-10-12 @tab
Title: @i{NodeBrain Tutorial}@*
Author: Ed Trettevik <eat@@nodebrain.org>@*
Publisher: NodeBrain Open Source Project

@item 2010-12-31 @tab
Release 0.8.3
@itemize @bullet
@item Updates - still needed
@end itemize

@end multitable

@page
@b{Preface}

@sp 1
This manual is intended for users of the Snmptrap NodeBrain Module, a plug-in for statistical anomaly detection.
The Baseline module was first introduced in NodeBrain 0.8.3 in September 2010.
This module should be treated as a prototype.  It has not yet been exercised enough to fully validate the design.
We expect it to evolve as we gain experience.


This tutorial is intended for readers seeking an introduction to NodeBrain through a series of simple examples. Other documents are available for readers looking for a more complete reference to the rule language, modules, or API (application programmatic interface).

The intent of the examples in this tutorial is to illustrate individual concepts, not to provide complete working applications or show all related options.
We avoid formal syntax descriptions, thinking you are here because you want to figure it out from examples.  

Files referenced in this tutorial are included in the tutorial directory of the NodeBrain distribution.  

See www.nodebrain.org for more information and the latest update to this document.

@include conventions.texi

@end titlepage

@end iftex

@c ----------------------------------------------------------
@c Not printed document

@ifnottex
@node Top
@top Snmptrap NodeBrain Module

This manual is for the Snmptrap NodeBrain Module (version @value{VERSION}, @value{UPDATED-MONTH}) used for receiving events via SNMP traps.
@*@*
Copyright @copyright{} 2014 Ed Trettevik <eat@@nodebrain.org>

@quotation
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License, Version 1.2 or any later version published by the Free Software Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included in the section titled @i{GNU Free Documentation License} at the end of this document.
@end quotation
@ifnotplaintext
@b{Short Table Of Contents}
@menu
* Concepts:: Foundation
* Tutorial:: Introduction by Example
* Commands:: Syntax and Semantics
* Triggers:: Conditions and Response
@end menu
@menu
* GNU Free Documentation License::
* Index::
@end menu
@end ifnotplaintext
@end ifnottex

@c Set page footings
@oddfooting @thistitle @| @| @thispage
@evenfooting @thispage @| @| @thistitle

@c Contents
@oddheading @| @| 
@evenheading @| @|
@contents

@c Set page headings for document
@oddheading @thischapter @| @| @value{UPDATED-MONTH}
@evenheading @value{UPDATED-MONTH} @| @| @thischapter


@node Concepts
@chapter Concepts
@cindex concepts

The Snmptrap module provides a node that monitors SNMP V1 and V2 traps.  This node listens on a specified port and interface for SNMP traps. By default, it listens to port 162 on all interfaces.

@cartouche
@smallexample

	define snmptrap node snmptrap; # default to port 162
	define snmptrap node snmptrap(50162); # alternate port
	define snmptrap node snmptrap("127.0.0.1"); # interface address
	define snmptrap node snmptrap("127.0.0.1:50162"); # both
@end smallexample
@end cartouche

When a trap is received, the node sends an alert command to its own context. Since this module is not MIB aware, the generated alert command references NodeBrain terms that are single quoted OIDs.

@cartouche
@smallexample
	alert '<oid>'=<value>,@dots{};
@end smallexample
@end cartouche

You can reference these OID terms in you NodeBrain rules or define aliases as illustrated in the example below.

@cartouche
@smallexample
define snmptrap node snmptrap;
snmptrap. define snmpTrap      cell '1.3.6.1.6.3.1.1.4.1.0';
snmptrap. define myMsgText     cell '1.3.6.1.4.1.2789.2005.1';
snmptrap. define myRestartTrap cell snmpTrap="1.3.6.1.4.1.2789.2005.0.2476317";
snmptrap. define r1 if(myRestartTrap and myMsgText~~"WWW"):$ - echo "$$@{myMsgText@}"
@end smallexample
@end cartouche

To send your own traps to this node, you will need a utility for sending traps.  Examples are shown below using the snmptrap in the Net-SNMP package.

@cartouche
@smallexample
snmptrap -v 1 -d -c public localhost .1.3.6.1.4.1.2789.2005 localhost 6 2476317 '' \
          .1.3.6.1.4.1.2789.2005.1 s "WWW Server Has Been Restarted"

snmptrap -v 2c -d -c public localhost '' .1.3.6.1.6.3.1.1.5.3 \
          ifIndex i 2   ifAdminStatus i 1    ifOperStatus i 1

@end smallexample
@end cartouche

@node Tutorial
@chapter Tutorial
@include nb_snmptrap_tutorial.texi

@node Commands
@chapter Commands
@cindex commands

@section Define
@cindex define command

@node Triggers
@chapter Triggers
@cindex Triggers

This module generates an @code{alert} for every trap received.

@node GNU Free Documentation License
@unnumbered GNU Free Documentation License
@include fdl.texi

@node Index 
@unnumbered Index 
@printindex cp 
@bye 
